variable "prefix" {}
variable "security_group_id" {}
variable "subnet_ids" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "vpc_id" {}
variable "aws_region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
